### PR TITLE
6.3.1 #450 migration AFTER start systemd

### PR DESCRIPTION
**Pull request by MadMan247**
## Problem

DB migration failed

## Solution

Put it after the service is started, per the official documentation.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

I installed a new peertube instance, uploaded a few videos, upgraded to this branch. It worked just fine. Please modify to your heart's content.

I also [upgraded my main instance](https://paste.yunohost.org/raw/riwukefemo) after creating a full backup.

Install log (YNH provided 6.2.1): https://paste.yunohost.org/raw/nagipabeyi

Upgrade log (this branch 6.3.0): https://paste.yunohost.org/raw/ijugurecox

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

Could I become a member of the ynh apps organization so that I may run these tests? I would like to become more involved with yunohost.

### CODE REVIEW

**Comment by MadMan247** [comment]
Clearly I don't know enough about github. Sorry. I thought I could be clean by trying to merge this straight into ericgaspar's 3.6.0 branch.
#450 but with a single extra commit.

Please test and merge.

I added a `sleep 20`, which may be optional. I did not check. I though 20 seconds was enough to ensure peertube was running, and short enough to be negligible for an upgrade. Arbitrary otherwise.

Thank you for your efforts!

**Comment by MadMan247** [comment]
```
# Remove old log file
ynh_secure_remove --file="$data_dir/logs"`
```
From the upgrade script. Why do we want to get rid of old logs?

image
Upgraded my instance. I will test again, since I did not have videos on the instance that I upgraded. I also tested before I did the bump version commit. Please review and merge.

**Comment by ericgaspar** [comment]
closing with #454

**Comment by MadMan247** [comment]
Look, I get that I didn't do a lot here, but the point was to get it to a state where it worked, since you had seemed to drop it before getting it there with pr 450. I would have liked if you would have run the CI tests to see if it fixed the issue before closing it.
Alright, let's go! Pull request 454! You worked on it for a few hours, and have you dropped it again? If I'm not allowed to contribute to it, could you please at least re-run the CI tests on 454? Since you had last updated the upgrade script to fix what I presume was the issue? I'm not running bookworm, and thus do not want to test it myself.

**Comment by ericgaspar** [comment]
#450 was closed because the changes you proposed were incorporated into #454. So your work was not in vain in any way.
The CI is currently very buggy with many failed jobs due to the server migration in our infra... We will have to wait I'm afraid

**Pull request closed without merging**
