### PR TITLE
Upgrade to 4.1.0~ynh1

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Upgrade to 4.1.0~ynh1*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by fflorent** [comment]
LGTM (modulo the test passes). You can also remove the `sources/patches-4.0.0` folder which is not useful anymore.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
Own CI result for Revision: 1f64101d6c1391fb8a49c26af2323bb856878bb5

image

**Pull request merged**
