### PR TITLE
don't remove admin_pass

### LINKED ISSUE #390: upgrade to version from 5.2.0~ynh1 to 5.2.1~ynh1 failed.
upgrade to version from 5.2.0~ynh1 to 5.2.1~ynh1 failed.

ERROR - peertube could not be upgraded: An error occurred in the app upgrade script.

https://paste.yunohost.org/raw/saniraqamo

### LINKED ISSUE #416: Upgrade from 5.2.1 to 6.0.2 fails
Here's the yunopaste. Any ideas?

https://paste.yunohost.org/raw/agabodumig

### PR DESCRIPTION
**Pull request by ericgaspar**
Fix #416 
Fix #390 

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
#414 failed for someone https://paste.yunohost.org/raw/kijokukagu

> WARNING - ./upgrade: line 16: admin: unbound variable
> DEBUG - + admin_mail=
> DEBUG - + ynh_exit_properly

I bet this PR solves it ?

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request merged**
