### PR TITLE
Upgrading npm and install yarn the corepack way

### LINKED ISSUE #421: New install fails (6.0.2~ynh3)
### Describe the bug
I had to uninstall the old version of peertube because I had a problem upgrading from 5.2.0~ynh1 to 5.2.1~ynh1.
When I try to install this new version (6.0.2~ynh3), the installation fails. 

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 11.2.9.1 (stable)
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Logs

https://paste.yunohost.org/raw/kalezerehe

### PR DESCRIPTION
**Pull request by tituspijean**
Attempt to fix #421 

- [ ] Propagate to upgrade script

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by lapineige** [comment]
!testme

**Comment by tituspijean** [comment]
(Note that I'm still debugging a user over at #421)

**Comment by tituspijean** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
Should be handled by the Node helper. Closing.

**Pull request closed without merging**
