### PR TITLE
Testing

### LINKED ISSUE #394: Peertube cassé, restauration sauvegarde impossible, mais J'ai trouvé une solution
**Petite explication avant la solution....**
Depuis quelque semaine impossible de mettre a jour peertube vers la 5.2.1, c’était pas grave je suis resté en 5.2.0.
Mais avant hier j'ai testé encore et la maj à fait planté complètement l'instance PeerTube. Yunohost lui n'avait pas de problèmes.
Et là le drame, la sauvegarde ne permet pas la réinstallation... plantage systématique.... même avec une sauvegarde plus ancienne.
Bref j'efface complètement peertube et lance l'installation d'un nouveau peertube... et la impossible d'installer...

**J'ai donc fait la procédure de migration pour réinstaller mon instance à la date de la sauvegarde:**
https://docs.joinpeertube.org/maintain/migration

Voici vite fait ma démarche, c'est sûrement imparfait, j'ai tâtonné et je l'écris de mémoire, mais ça peut être une piste pour certains d'entre vous.

1. copier le repertoire des données
2. copier la partie config
3. dumper la DB de postgresql en trouvant le pass de la db dans la partie config
4. j'ai effacé le répertoire peertube qui était dans yunohost.app (qui ne voulaient pas partir malgré la désinstallation) - cela faisait planté la nouvelle installation vierge visiblement.
5. Reinstallation vierge de peertube avec le même domain
6. je stop peertube
7. Reinjection de la DB
8. copier des fichiers de données
9. Copie les fichiers de config
10. ajustement du mot de passe de la DB dans le fichier de config (récupéré dans le nouveau fichier de config)

Courage, si vous avez une sauvegarde rien n'est perdu !!!!

### PR DESCRIPTION
**Pull request by ericgaspar**
- package version 2
- upgrade PeerTube to version 6.0.2
- Fix #394

Was #408

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Was that manually testing, including upgrade and uploading a video ?
I'll probably do it later today.

Please wait for manual test*s* before merging :)

**Comment by lapineige** [comment]
Tested on one server, it went fine :smiley:. Including old and new videos.
Testing on another one right now…

**Comment by lapineige** [comment]
The other server was good.
Another report in the forum confirm it fixed the previous buggy update: https://forum.yunohost.org/t/peertube-app-from-5-2-1-to-6-0-2-doesnt-work-at-all-videos-dont-start/27791/16

Let's merge ! :tada:

**Review by lapineige — APPROVED** [review]

**Pull request merged**
