### PR TITLE
Create log file

### PR DESCRIPTION
**Pull request by tituspijean**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
This was an attempt to fix #431, but Jibec reported that it does not solve the issue. :/

**Comment by fflorent** [comment]
@tituspijean It may not solve the issue, but can we still merge this PR, as the upstream upgrade fixes a security issue?

**Comment by tituspijean** [comment]
Oh sure, I did not notice the upgrade :)

**Pull request merged**
