### PR TITLE
Fixes

### LINKED ISSUE #311: When Upgrade to 4.1 - Prosody install breaks metronome XMPP service
### Describe the bug
After an update of Peertube to 4.1 It seems the service XMPP metronome was crashed and it doesn't work anymore
### Context

- Hardware: *QEMU VM on proxmox x86 host
- YunoHost version: 4.3.6.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Peertube 4.1

### Steps to reproduce

Try to use your xmpp yunohost account on your default domain.tld 
The client says :
le serveur n'est pas responsable pour ce domaine yunohost

### Expected behavior

The client must say :
Connected

### Corrective action resolved the incident on metronome and XMPP yunohost service but not resolved the problem on prosody peertube

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo systemctl stop prosody
    sudo systemctl start metronome
    ```
The XMPP service works again, not tested the impact ion peertube when i desactivated prosody.

### Logs

nothing

### LINKED ISSUE #347: Prosody doesn't work
- Hardware: *Old computer*
- YunoHost version: 11.0.9.14
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: Prosody 5.7.1 with PeerTube 4.2.2

### Steps to reproduce

   1. *Install PeerTube via appstore*
   2. *Open port for live streaming*
   3. *Enable LiveChat Prosody server controlled by PeerTube*
   4. *Start the live streaming*
   5. *Go to live streaming video page*

### Expected behavior

*The livechat plugin doesn't work/just show Prosody Logo*

### Logs
https://paste.yunohost.org/ugoligamoj

*If applicable and useful, add screenshots to help explain your problem.*
prosody screenshot

### LINKED ISSUE #358: Stuck at "Starting a systemd service" for hours
Updating it from 4.3.1 ynh1 to ynh2 I see this for hours:

```
Now upgrading peertube...
Loading installation settings...
Checking version...
Backing up the app before upgrading (may take a while)...
Stopping a systemd service...
Ensuring downward compatibility...
NOTICE: extension "unaccent" already exists, skipping
NOTICE: extension "pg_trgm" already exists, skipping
'/etc/apt/sources.list.d/yarn.list' wasn't deleted because it doesn't exist.
'/usr/share/yunohost/hooks/conf_regen/15-nginx_peertube' wasn't deleted because it doesn't exist.
'/home/yunohost.app/peertube/storage/logs' wasn't deleted because it doesn't exist.
Making sure dedicated system user exists...
Upgrading dependencies...
Upgrading NGINX web server configuration...
Creating a data directory...
Building Yarn dependencies...
Updating a config file...
File /var/www/peertube/config/local-production.json has been manually modified since the installation or last upgrade. So it has been duplicated in /var/cache/yunohost/appconfbackup//var/www/peertube/config/local-production.json.backup.20221211.153248
Upgrading systemd configuration...
Starting a systemd service...
(this may take some time)
```

No other input. Opening the ynh admin dashboard in another tab prevents me from accessing the updates for instance, same as it does when a ynh process is running. Maybe it is a bug in the latest package version?

### LINKED ISSUE #375: Livechat plugin v6.0.0+ do not require prosody_ynh anymore
Direct feedback from @JohnXLivingston during the JDLL:

Since its version [v6.0.0](https://github.com/JohnXLivingston/peertube-plugin-livechat/releases/tag/v6.0.0), the chat plugin relies on Prosody AppImage, which means we don't need prosody_ynh anymore, thus not disabling Metronome.

This is valid for all architectures except ARM, he's working on it.

### LINKED ISSUE #382: Adapt the package to work with the runners
Please follow our discussion here https://github.com/Chocobozzz/PeerTube/issues/5849 - it seems that with the new "runners" feature the nginx file must be adapted.

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Bookworm level 0*

## Solution

- * Fix #382*
- * Fix #375 ; Fix #311 ; Fix #347*
- * Fix #358*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme
!bookwormtestme

**Comment by yalh76** [comment]
!testme
!bookwormtestme

**Comment by yalh76** [comment]
!testme
!bookwormtestme

**Comment by JohnXLivingston** [comment]
Thanks!

**Pull request merged**
