### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
Upgrade to version 5.1.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by tio-trom** [comment]
The test seems all good. Would you merge this into main? Peertube implemented a feature to stop the bots from registering and I cannot wait to update my instance that gets blasted with bots :D

**Comment by tio-trom** [comment]
Tested with my main instance all works great. Here is the log https://paste.trom.tf/uyinazofel.sql

Login/registrations work. Video upload and transcoding work. Playback and all that. All seems good. Please push to main.

**Review by alexAubin — APPROVED** [review]

**Comment by TILvids** [comment]
5.0.1 update completely broke our secondary instance, and I had to revert the server. I'll try this again on the secondary server once it goes up, and see how it goes.

**Comment by alexAubin** [comment]
@TILvids : can you elaborate what you man by "completely broke" ?

**Comment by alexAubin** [comment]
(Note that this is an upgrade from 5.0.1 to 5.1.0 ... can you confirm that you upgrade to 5.1.0 ? Or to 5.0.1 ?)

**Comment by TILvids** [comment]
I have not upgraded to 5.x yet, as the last yunohost peertube update made my server completely unresponsive (web server would not come online). So I'm still on 4.x. I will try upgrading to 5.1.0 when it's available.

**Comment by tio-trom** [comment]
Try deactivating all plugins. Then update. See if that works. As confirmed for me worked perfectly fine to upgrade from 5.0.1 to 5.1.0.

**Comment by fflorent** [comment]
Made the upgrade on my own PeerTube test instance, worked as expected :)

**Comment by TILvids** [comment]
I'm still on 4.3.1 (never could get it to upgrade last time) so I'll try disabling all plugins and try again when this gets merged into master. I think when we were trying to dig through the logs last time, it looked like something wasn't waiting long enough to come back up, and the upgrade timed out.

**Pull request merged**
