### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Let's merge it right away to avoid faulty upgrades from master ?

**Comment by ericgaspar** [comment]
it is merge a bit too quickly... `__ADMIN_PASS__` doesn't get replace in `POST_UPGRADE.md` file

**Comment by lapineige** [comment]
Oh, too bad 😅
At least it's only blocking for new installs, while it doesn't break upgrade (as they were before). So it's not (as much of) a hurry to fix it.

**Comment by ericgaspar** [comment]
> So in fact we are sending the Admin password again to users after the upgrade ? Why ?
The `POST.INSTALL.md` message is displayed temporarily in the app admin page. Once you click the green button, it's gone... so It may be a good idea to display it after upgrade. (this message was formerly sent by email so was a little more persistent...)

**Comment by lapineige** [comment]
Oh that's why I didn't receive it, and didn't see it as I was trying it in CLI.
Well that's more secure like this...
But this is stored as a setting, so users could access to it afterwards if needed, right ? It's not the best UX and the most accessible option, but at least it exists.

**Pull request merged**
