### PR TITLE
Added upgrade file,port change option and multi-instance

### PR DESCRIPTION
**Pull request by anmol26s**
1. changed sleep to 15 as suggested here https://github.com/YunoHost-Apps/peertube_ynh/issues/5#issue-307784355
2. Added working upgrade
3. Option to change the port
4. Store videos in /home/yunohost.app/app directory issue https://github.com/YunoHost-Apps/peertube_ynh/issues/8

### CODE REVIEW

**Comment by anmol26s** [comment]
Need help with 
1. Better handling of password issue https://github.com/YunoHost-Apps/peertube_ynh/issues/12.
2. How to backup home folder? eg. /home/yunohost.app/$app can be huge for peertube which can fill up space on bakup.
3. Handle backports like dependencies so that other app don't remove it https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/install#L88-L90
4. Issue https://github.com/YunoHost-Apps/peertube_ynh/issues

Thanks

**Comment by Rafi594** [comment]
Hi

- For the backup you can add backup_core_only https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/backup#L77-L88

**Comment by Jibec** [comment]
maybe the storage folder could be accessed by SFTP so data backups can be done easily ?

https://github.com/YunoHost-Apps/my_webapp_ynh/blob/master/scripts/install#L103

**Comment by anmol26s** [comment]
@Jibec 
Its better to install app with password. The command is already implemented but the command give error on special characters like ( or ) https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/install#L201. There must me more sophisticated way of echoing password.
Please explain me why the permission are not good in  chown -R $app:$app "$final_path" "$datadir" ? Is it a security risk ? 

For backup of home folderI propose 3 options:
1. Ask the user at the time of  installation if the backup of home should be done while backup and give the warning that backup could be large if it has many videos.
2. Create an other app peertube_backup which can backup and restore the home folder. But we already have Archivist app https://github.com/YunoHost-Apps/archivist_ynh (Thanks to wonderful work of @maniackcrudelis ) which kind of solve the necessity of creating this app. We can mention this app in the readme.
3. SFTP support as suggested by @Jibec 

Please provide more logical way to do this and give feedback about which is better way.

**Comment by Jibec** [comment]
About password: ask less and make sure it will not crash your install sounds better to me. I'm unsure any password provided by user will really be better than 24 or more characters. And the app should provide the way to change it.

About rights, the principle is as follow: the less you give the better it is. The limit is to be fixed by you. If you have a dedicated folder for data, I assume it means other contents doesn't have to be modified by the app, so there is no reason to give the right. In addition, I'm unsure any usage is done by setting the $app group.

BTW, I fixed upgrade, I'm trying to finish the restore script. I'll use the current PR on anmol:master to bring you my way of fixing it.

I don't know I'm doing this, I just feel like it...

**Comment by anmol26s** [comment]
Thanks to @Jibec  for lot of cleaning and improvement of the code.
Issue 1 is solved and 2 can be handle in future if someone has an issue with it. For 3 separate issue can be opened.
Merging in testing.

**Pull request merged**
