### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
```
72329 INFO [#+..................] > Restoring the PostgreSQL database...
72441 WARNING psql: error: FATAL:  Peer authentication failed for user "peertube"
```

(this may be due to a bug in the CI due to me implementing preinstall of the apt dependencies on the CI to speed stuff up, but the bug should be fixed now)

**Comment by lapineige** [comment]
This really need manual testing (in depth), merging this in testing prevents us from merging other upgrades before this is merged...

**Comment by alexAubin** [comment]
The only thing really changing is the addition of the change_url script though ...

**Review by alexAubin — APPROVED** [review]

**Comment by lapineige** [comment]
Yes, but I don't want users to believe this can work and end up with a broken instance, especially has it could mess with federation.

**Comment by ericgaspar** [comment]
If this is not working with federation, let's remove it then.

**Comment by lapineige** [comment]
WTF ?

I mean it requires *testing* (and a serious one) to be sure it works well, especially with federation, not that it does work... why are you trashing that work ? :cry:

**Pull request closed without merging**
