### PR TITLE
v1.2.0 released

### PR DESCRIPTION
**Pull request by samvermeulenpro**
https://github.com/Chocobozzz/PeerTube/releases/tag/v1.2.0

### CODE REVIEW

**Comment by rigelk** [comment]
New configuration options need to be taken into account, and breaking changes to the Nginx conf too.

**Comment by anmol26s** [comment]
@rigelk 
Do you mean the nginx configuration?

**Comment by rigelk** [comment]
@anmol26s please refer to the release notes.

**Comment by anmol26s** [comment]
@samvermeulenpro 
I have updated the peertube package. The package needed changes in other configurations too, other then updating upstream only.
Closing this.

**Comment by samvermeulenpro** [comment]
Very well, thank you ;)

**Pull request closed without merging**
