### PR TITLE
Add change url

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by lapineige** [comment]
Wow you actually did it 😲

For anyone reading this : feedback on actual servers (federated or not) will be valuable here 🙂
It's strongly advised to test this on instances dedicated to such test, not on a production server. Testing federation before and after would be very useful (be aware that data can stay in cache of remote federated servers).

**Comment by lapineige** [comment]
#422 (comment)
Reopening in dedicated branch that will allow proper testing at a slow pace.

Testers needed ! 😃

**Comment by ericgaspar** [comment]
Closing... This is not related to change_url script. will rework something properly

**Comment by lapineige** [comment]
I don't understand everything but alright :)

**Pull request closed without merging**
