### PR TITLE
Merge testing into master

### PR DESCRIPTION
**Pull request by anmol26s**

### CODE REVIEW

**Comment by alexAubin** [comment]
0jnxn

**Comment by anmol26s** [comment]
I think we should stop the peertube service in the **upgrade script**  before the actual update commands run. I had to manually reload the peertube service and nginx to actually reflect the update in the web interface.
Moreover we should reload the nginx after the password is created and sent to the email in the **install script** to fix this issue https://github.com/YunoHost-Apps/peertube_ynh/issues/19

**Comment by anmol26s** [comment]
The app have the option to be inside SSO. I don't know if this is good idea or serve any purpose for a confining the videos to particular users, as we already have authentication for this in Peertube. 
I think  the app should be public by default.

**Comment by alexAubin** [comment]
>Someone pointed out ffmpeg is present in Debian stretch. So we need to decide if backports is needed on Debian stretch.

As far as I understand, their aren't. You should handle this the same way that what's done for roundcube I guess : https://github.com/YunoHost-Apps/roundcube_ynh/pull/35/files

**Comment by anmol26s** [comment]
> As far as I understand, their aren't. You should handle this the same way that what's done for roundcube I guess : https://github.com/YunoHost-Apps/roundcube_ynh/pull/35/files
Done! Thanks for the hint.

**Comment by anmol26s** [comment]
Smtp settings needs to be configured  https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/conf/production.yaml#L32, so that app can send email. Any idea what should be the settings value and will it be same for Jessie and Stretch ?

**Comment by alexAubin** [comment]
>Smtp settings needs to be configured https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/conf/production.yaml#L32, so that app can send email. Any idea what should be the settings value and will it be same for Jessie and Stretch ?

Uuughh, mail stuff...

Weeeell, I see that it apparently use propre mail submission, which is : 
- nice, because since the submission is properly authenticated (c.f. login / password) the mail will be signed by DKIM and will have a higher chance of not being flagged as spam.
- buuuut that also mean we need a login / password here.

As far as I know, only real yunohost user (created with `yunohost user create` and therefore LDAP users) can properly authenticate... So a dirty hack for this could be to create a user peertube for this, but that's not really satisfying (user will show up in user lists and so on ...). Thing is, other apps need to send emails something and would like to have the DKIM-signed thing. So imho the long term solution is to tweak yunohost's postfix conf to allow other, regular system users to authenticate.

So I don't have a magic setting to suggest ...

Other detail is that the `from_address` should match the identify of the user authenticating, i.e. you can't send a mail on behalf of `admin` if you're not `admin` (or the user owning the alias)

Also small detail : yes, the port is going to change between jessie (465) to stretch (587) because 465 is actually a deprecated thing.

**Comment by anmol26s** [comment]
@Jibec 
The restore of the app fails on Debian Stretch.

**Comment by anmol26s** [comment]
Should we have encoding to UTF8 while restoring too?
https://github.com/YunoHost-Apps/peertube_ynh/blob/testing/scripts/install#L120

**Comment by anmol26s** [comment]
We should do this commit https://github.com/YunoHost-Apps/etherpad_mypads_ynh/pull/35/commits/35ef8e1cad11533f2cd1201534514084de519151 for peertube too, to solve the mail sending error https://github.com/YunoHost-Apps/etherpad_mypads_ynh/issues/34.

**Comment by Jibec** [comment]
I can't help you anmol, there is too much commits, I can't follow up.
When testing tonight, even simple connection as root doesn't work on stretch.

**Comment by anmol26s** [comment]
`When testing tonight, even simple connection as root doesn't work on stretch.`
Do you mean the root user? Can I have the log?

**Comment by anmol26s** [comment]
I am using mail setting without DKIM for now. The readme has been updated for a hint to which file has to be edited to have a proper SMTP if someone wants it.

**Comment by anmol26s** [comment]
I think, its time to merge into master. The app looks in working state. Remaining warnings can be handled when the CI checks the scripts.
 Only one issue remains which is about the backup.As the Peertube home directory with lot of videos will grow very fast and backing up will eat up lot of space on the server. Moreover there can be times where the Peertube home directory is so huge that there is no space to backup on the server. The app also gets backed up when the upgrade script is ran and big peertube home directory can take long time, frustrating the end user. I am ignoring this issue for now and keep it for later discussion.

**Pull request merged**
